workspace:
  base: /go
  path: src/github.com/abaeve/auth-bot

pipeline:
  build:
    image: golang:1.8
    commands:
      - export GOPATH=/drone
      - export PATH=$PATH:$GOPATH/bin
      - go get github.com/micro/micro
      - go get github.com/abaeve/services-common/config
      - cd $GOPATH/src/github.com/micro/micro
      - git remote add abafork https://github.com/abaeve/micro
      - git fetch abafork fork
      - git checkout fork
      - cd $GOPATH/src/github.com/micro/go-bot
      - git remote add abafork https://github.com/abaeve/go-bot
      - git fetch abafork fork
      - git checkout fork
      - cd $GOPATH/src/github.com/abaeve/auth-bot
      - go get -t -v ./...
      - cd background
      - go test
      - cd ../command
      - go test
      - cd ../discord
      - go test
#      - go get github.com/mattn/goveralls
#      - goveralls -service=drone.io -repotoken=${REPOTOKEN}
